# Generated by Django 5.2.4 on 2025-08-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageprompt',
            name='prompt_image',
            field=models.ImageField(upload_to='images_for_automation/'),
        ),
    ]
